services:
    nginx-proxy:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - '10000:80'
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: flask/Dockerfile
