services:
    nginx-proxy:
        image: nginx
        ports:
            - 10000:80
        volumes:
            - type: bind
              source: ./nginx/
              target: /etc/nginx/conf.d/
              read_only: true
            - type: bind
              source: ./web
              target: /data/web
              read_only: true
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: flask/Dockerfile
