services:
    nginx-proxy:
        image: nginx
        ports:
            - 10000:80
        volumes:
            - type: bind
              source: ./nginx
              target: /etc/nginx/templates
              read_only: true
            - type: bind
              source: ./web
              target: /data/web
              read_only: true
        depends_on:
            - backend
        environment:
            - PROXY_HOSTNAME=localhost
            - PROXY_PORT=10000
            - NGINX_PORT=80
    backend:
        build:
            context: .
            dockerfile: flask/Dockerfile
        stop_signal: SIGINT
