services:
    nginx-proxy:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - '10000:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: flask/Dockerfile
