services:
    nginx-proxy:
        image: nginx
        ports:
            - $OUTPORT:80
        volumes:
            - type: bind
              source: ./nginx
              target: /etc/nginx/templates
              read_only: true
            - type: bind
              source: ./web
              target: /data/web
              read_only: true
        depends_on:
            - backend
        environment:
            - PROXY_HOSTNAME=localhost
            - PROXY_PORT=$OUTPORT
            - NGINX_PORT=80
    backend:
        build:
            context: .
            dockerfile: flask/Dockerfile
        volumes:
            - wav-files:/src/flask/static
    alpine-cron:
        build:
            context: .
            dockerfile: cron/Dockerfile
        environment:
            - CURL_PORT=6500
            - CURL_HOST=backend
        depends_on:
            - nginx-proxy
        init: true
        volumes:
            - wav-files:/src/static
volumes:
    wav-files: